server:
  port: 8282

spring:
  # DATABASE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://localhost:3306/cogdb?createDatabaseIfNotExist=true
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

# JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
logging:
  level:
    org:
      hibernate:
        type: trace
