server:
  port: 8283

spring:
  # DATABASE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://localhost:3306/cogdb?createDatabaseIfNotExist=true
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: 1234
