server:
  port: 8081
  servlet:
    context-path: /jwt-resource-server

####### resource server configuration properties
spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9191/auth/realms/baeldung
          jwk-set-uri: http://localhost:9191/auth/realms/baeldung/protocol/openid-connect/certs